export const bancasExamples: Record<string, any[]> = {
  "CESPE": [
    {"banca": "CESPE", "enunciado": "Julgue o item: Se p e q são proposições simples, então a proposição p -> q é equivalente a ~p v q.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "Julgue o item: A negação da proposição 'Se chove, então faz frio' é 'Chove e não faz frio'.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "Em uma progressão aritmética, o primeiro termo é 5 e a razão é 3. O décimo termo é 32.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "Se log(x) = 2, então x = 100.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A soma dos ângulos internos de um triângulo é 180 graus.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A negação de 'Todo homem é mortal' é 'Nenhum homem é mortal'.", "gabarito": "ERRADO"},
    {"banca": "CESPE", "enunciado": "Se x² = 16, então x é necessariamente 4.", "gabarito": "ERRADO"},
    {"banca": "CESPE", "enunciado": "A probabilidade de sair cara em um lançamento de moeda honesta é 0,5.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "Em um conjunto de 10 pessoas, o número de duplas possíveis é 45.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A função f(x) = 2x + 3 é uma função crescente.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "O valor de 5! é 120.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A raiz quadrada de 144 é 12.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "Se sen(x) = 1, então x pode ser 90 graus.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "O volume de um cubo de aresta 2 é 8.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A área de um círculo de raio 1 é pi.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "O número 2 é o único primo par.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "A interseção de dois conjuntos vazios é um conjunto unitário.", "gabarito": "ERRADO"},
    {"banca": "CESPE", "enunciado": "Se A está contido em B, então a união de A e B é B.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "O MDC de 12 e 18 é 6.", "gabarito": "CERTO"},
    {"banca": "CESPE", "enunciado": "O MMC de 4 e 6 é 12.", "gabarito": "CERTO"}
  ],
  "FCC": [
    {"banca": "FCC", "enunciado": "Um capital de R$ 1.000,00 aplicado a juros simples de 2% ao mês, após 5 meses, resultará em um montante de:", "alternativas": ["A) R$ 1.100,00", "B) R$ 1.050,00", "C) R$ 1.200,00", "D) R$ 1.150,00", "E) R$ 1.020,00"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "A negação da proposição 'João é médico ou Maria é enfermeira' é:", "alternativas": ["A) João não é médico ou Maria não é enfermeira", "B) João não é médico e Maria não é enfermeira", "C) Se João não é médico, então Maria não é enfermeira", "D) João é médico e Maria não é enfermeira", "E) Maria é enfermeira e João não é médico"], "gabarito": "B"},
    {"banca": "FCC", "enunciado": "Se 3 operários constroem um muro em 10 dias, 5 operários construirão o mesmo muro em:", "alternativas": ["A) 6 dias", "B) 16,6 dias", "C) 8 dias", "D) 4 dias", "E) 12 dias"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O valor de x na equação 2x + 5 = 13 é:", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "B"},
    {"banca": "FCC", "enunciado": "A média aritmética de 10, 20 e 30 é:", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 10"], "gabarito": "B"},
    {"banca": "FCC", "enunciado": "Quantos são os anagramas da palavra CASA?", "alternativas": ["A) 24", "B) 12", "C) 6", "D) 4", "E) 48"], "gabarito": "B"},
    {"banca": "FCC", "enunciado": "Um triângulo retângulo tem catetos 3 e 4. A hipotenusa mede:", "alternativas": ["A) 5", "B) 7", "C) 12", "D) 25", "E) 1"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "Se log2(x) = 3, então x é:", "alternativas": ["A) 6", "B) 8", "C) 9", "D) 5", "E) 1"], "gabarito": "B"},
    {"banca": "FCC", "enunciado": "A soma dos 10 primeiros números naturais ímpares é:", "alternativas": ["A) 100", "B) 50", "C) 110", "D) 90", "E) 200"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O valor de 20% de 50% de 100 é:", "alternativas": ["A) 10", "B) 20", "C) 5", "D) 50", "E) 2"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "Em uma urna com 5 bolas brancas e 5 pretas, a probabilidade de tirar uma branca é:", "alternativas": ["A) 1/2", "B) 1/5", "C) 1/10", "D) 5/10", "E) A e D estão corretas"], "gabarito": "E"},
    {"banca": "FCC", "enunciado": "O perímetro de um quadrado de área 16 é:", "alternativas": ["A) 16", "B) 8", "C) 32", "D) 4", "E) 20"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "A solução do sistema x+y=5 e x-y=1 é:", "alternativas": ["A) (3,2)", "B) (2,3)", "C) (4,1)", "D) (1,4)", "E) (5,0)"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O volume de um cilindro de raio 1 e altura 2 é:", "alternativas": ["A) 2pi", "B) pi", "C) 4pi", "D) 2", "E) 1"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "Se f(x) = x² - 1, f(3) é:", "alternativas": ["A) 8", "B) 9", "C) 10", "D) 2", "E) 4"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O décimo termo da PA (2, 4, 6, ...) é:", "alternativas": ["A) 20", "B) 18", "C) 22", "D) 10", "E) 24"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "A razão de uma PG onde a1=3 e a2=6 é:", "alternativas": ["A) 2", "B) 3", "C) 1/2", "D) 9", "E) 18"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O valor de cos(0) é:", "alternativas": ["A) 1", "B) 0", "C) -1", "D) 1/2", "E) pi"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "A diagonal de um quadrado de lado L é:", "alternativas": ["A) L√2", "B) L√3", "C) 2L", "D) L/2", "E) L²"], "gabarito": "A"},
    {"banca": "FCC", "enunciado": "O número de subconjuntos de um conjunto com 3 elementos é:", "alternativas": ["A) 8", "B) 6", "C) 3", "D) 9", "E) 4"], "gabarito": "A"}
  ],
  "FGV": [
    {"banca": "FGV", "id": "FGV_01", "enunciado": "Questão de Matemática 1 da banca FGV: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_02", "enunciado": "Questão de Matemática 2 da banca FGV: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_03", "enunciado": "Questão de Matemática 3 da banca FGV: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_04", "enunciado": "Questão de Matemática 4 da banca FGV: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_05", "enunciado": "Questão de Matemática 5 da banca FGV: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_06", "enunciado": "Questão de Matemática 6 da banca FGV: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_07", "enunciado": "Questão de Matemática 7 da banca FGV: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_08", "enunciado": "Questão de Matemática 8 da banca FGV: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_09", "enunciado": "Questão de Matemática 9 da banca FGV: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_10", "enunciado": "Questão de Matemática 10 da banca FGV: Calcule o valor de 10 + 20.", "alternativas": ["A) 30", "B) 40", "C) 50", "D) 60", "E) 70"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_11", "enunciado": "Questão de Matemática 11 da banca FGV: Calcule o valor de 11 + 22.", "alternativas": ["A) 33", "B) 44", "C) 55", "D) 66", "E) 77"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_12", "enunciado": "Questão de Matemática 12 da banca FGV: Calcule o valor de 12 + 24.", "alternativas": ["A) 36", "B) 48", "C) 60", "D) 72", "E) 84"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_13", "enunciado": "Questão de Matemática 13 da banca FGV: Calcule o valor de 13 + 26.", "alternativas": ["A) 39", "B) 52", "C) 65", "D) 78", "E) 91"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_14", "enunciado": "Questão de Matemática 14 da banca FGV: Calcule o valor de 14 + 28.", "alternativas": ["A) 42", "B) 56", "C) 70", "D) 84", "E) 98"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_15", "enunciado": "Questão de Matemática 15 da banca FGV: Calcule o valor de 15 + 30.", "alternativas": ["A) 45", "B) 60", "C) 75", "D) 90", "E) 105"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_16", "enunciado": "Questão de Matemática 16 da banca FGV: Calcule o valor de 16 + 32.", "alternativas": ["A) 48", "B) 64", "C) 80", "D) 96", "E) 112"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_17", "enunciado": "Questão de Matemática 17 da banca FGV: Calcule o valor de 17 + 34.", "alternativas": ["A) 51", "B) 68", "C) 85", "D) 102", "E) 119"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_18", "enunciado": "Questão de Matemática 18 da banca FGV: Calcule o valor de 18 + 36.", "alternativas": ["A) 54", "B) 72", "C) 90", "D) 108", "E) 126"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_19", "enunciado": "Questão de Matemática 19 da banca FGV: Calcule o valor de 19 + 38.", "alternativas": ["A) 57", "B) 76", "C) 95", "D) 114", "E) 133"], "gabarito": "A"},
    {"banca": "FGV", "id": "FGV_20", "enunciado": "Questão de Matemática 20 da banca FGV: Calcule o valor de 20 + 40.", "alternativas": ["A) 60", "B) 80", "C) 100", "D) 120", "E) 140"], "gabarito": "A"}
  ],
  "VUNESP": [
    {"banca": "VUNESP", "id": "VUNESP_01", "enunciado": "Questão de Matemática 1 da banca VUNESP: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_02", "enunciado": "Questão de Matemática 2 da banca VUNESP: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_03", "enunciado": "Questão de Matemática 3 da banca VUNESP: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_04", "enunciado": "Questão de Matemática 4 da banca VUNESP: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_05", "enunciado": "Questão de Matemática 5 da banca VUNESP: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_06", "enunciado": "Questão de Matemática 6 da banca VUNESP: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_07", "enunciado": "Questão de Matemática 7 da banca VUNESP: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_08", "enunciado": "Questão de Matemática 8 da banca VUNESP: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_09", "enunciado": "Questão de Matemática 9 da banca VUNESP: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_10", "enunciado": "Questão de Matemática 10 da banca VUNESP: Calcule o valor de 10 + 20.", "alternativas": ["A) 30", "B) 40", "C) 50", "D) 60", "E) 70"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_11", "enunciado": "Questão de Matemática 11 da banca VUNESP: Calcule o valor de 11 + 22.", "alternativas": ["A) 33", "B) 44", "C) 55", "D) 66", "E) 77"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_12", "enunciado": "Questão de Matemática 12 da banca VUNESP: Calcule o valor de 12 + 24.", "alternativas": ["A) 36", "B) 48", "C) 60", "D) 72", "E) 84"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_13", "enunciado": "Questão de Matemática 13 da banca VUNESP: Calcule o valor de 13 + 26.", "alternativas": ["A) 39", "B) 52", "C) 65", "D) 78", "E) 91"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_14", "enunciado": "Questão de Matemática 14 da banca VUNESP: Calcule o valor de 14 + 28.", "alternativas": ["A) 42", "B) 56", "C) 70", "D) 84", "E) 98"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_15", "enunciado": "Questão de Matemática 15 da banca VUNESP: Calcule o valor de 15 + 30.", "alternativas": ["A) 45", "B) 60", "C) 75", "D) 90", "E) 105"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_16", "enunciado": "Questão de Matemática 16 da banca VUNESP: Calcule o valor de 16 + 32.", "alternativas": ["A) 48", "B) 64", "C) 80", "D) 96", "E) 112"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_17", "enunciado": "Questão de Matemática 17 da banca VUNESP: Calcule o valor de 17 + 34.", "alternativas": ["A) 51", "B) 68", "C) 85", "D) 102", "E) 119"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_18", "enunciado": "Questão de Matemática 18 da banca VUNESP: Calcule o valor de 18 + 36.", "alternativas": ["A) 54", "B) 72", "C) 90", "D) 108", "E) 126"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_19", "enunciado": "Questão de Matemática 19 da banca VUNESP: Calcule o valor de 19 + 38.", "alternativas": ["A) 57", "B) 76", "C) 95", "D) 114", "E) 133"], "gabarito": "A"},
    {"banca": "VUNESP", "id": "VUNESP_20", "enunciado": "Questão de Matemática 20 da banca VUNESP: Calcule o valor de 20 + 40.", "alternativas": ["A) 60", "B) 80", "C) 100", "D) 120", "E) 140"], "gabarito": "A"}
  ],
  "CESGRANRIO": [
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_01", "enunciado": "Questão de Matemática 1 da banca CESGRANRIO: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_02", "enunciado": "Questão de Matemática 2 da banca CESGRANRIO: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_03", "enunciado": "Questão de Matemática 3 da banca CESGRANRIO: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_04", "enunciado": "Questão de Matemática 4 da banca CESGRANRIO: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_05", "enunciado": "Questão de Matemática 5 da banca CESGRANRIO: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_06", "enunciado": "Questão de Matemática 6 da banca CESGRANRIO: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_07", "enunciado": "Questão de Matemática 7 da banca CESGRANRIO: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_08", "enunciado": "Questão de Matemática 8 da banca CESGRANRIO: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "CESGRANRIO", "id": "CESGRANRIO_09", "enunciado": "Questão de Matemática 9 da banca CESGRANRIO: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ],
  "IBFC": [
    {"banca": "IBFC", "id": "IBFC_01", "enunciado": "Questão de Matemática 1 da banca IBFC: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_02", "enunciado": "Questão de Matemática 2 da banca IBFC: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_03", "enunciado": "Questão de Matemática 3 da banca IBFC: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_04", "enunciado": "Questão de Matemática 4 da banca IBFC: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_05", "enunciado": "Questão de Matemática 5 da banca IBFC: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_06", "enunciado": "Questão de Matemática 6 da banca IBFC: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_07", "enunciado": "Questão de Matemática 7 da banca IBFC: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_08", "enunciado": "Questão de Matemática 8 da banca IBFC: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "IBFC", "id": "IBFC_09", "enunciado": "Questão de Matemática 9 da banca IBFC: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ],
  "QUADRIX": [
    {"banca": "QUADRIX", "id": "QUADRIX_01", "enunciado": "Questão de Matemática 1 da banca QUADRIX: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_02", "enunciado": "Questão de Matemática 2 da banca QUADRIX: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_03", "enunciado": "Questão de Matemática 3 da banca QUADRIX: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_04", "enunciado": "Questão de Matemática 4 da banca QUADRIX: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_05", "enunciado": "Questão de Matemática 5 da banca QUADRIX: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_06", "enunciado": "Questão de Matemática 6 da banca QUADRIX: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_07", "enunciado": "Questão de Matemática 7 da banca QUADRIX: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_08", "enunciado": "Questão de Matemática 8 da banca QUADRIX: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "QUADRIX", "id": "QUADRIX_09", "enunciado": "Questão de Matemática 9 da banca QUADRIX: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ],
  "AOCP": [
    {"banca": "AOCP", "id": "AOCP_01", "enunciado": "Questão de Matemática 1 da banca AOCP: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_02", "enunciado": "Questão de Matemática 2 da banca AOCP: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_03", "enunciado": "Questão de Matemática 3 da banca AOCP: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_04", "enunciado": "Questão de Matemática 4 da banca AOCP: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_05", "enunciado": "Questão de Matemática 5 da banca AOCP: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_06", "enunciado": "Questão de Matemática 6 da banca AOCP: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_07", "enunciado": "Questão de Matemática 7 da banca AOCP: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_08", "enunciado": "Questão de Matemática 8 da banca AOCP: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "AOCP", "id": "AOCP_09", "enunciado": "Questão de Matemática 9 da banca AOCP: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ],
  "IDECAN": [
    {"banca": "IDECAN", "id": "IDECAN_01", "enunciado": "Questão de Matemática 1 da banca IDECAN: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_02", "enunciado": "Questão de Matemática 2 da banca IDECAN: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_03", "enunciado": "Questão de Matemática 3 da banca IDECAN: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_04", "enunciado": "Questão de Matemática 4 da banca IDECAN: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_05", "enunciado": "Questão de Matemática 5 da banca IDECAN: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_06", "enunciado": "Questão de Matemática 6 da banca IDECAN: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_07", "enunciado": "Questão de Matemática 7 da banca IDECAN: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_08", "enunciado": "Questão de Matemática 8 da banca IDECAN: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "IDECAN", "id": "IDECAN_09", "enunciado": "Questão de Matemática 9 da banca IDECAN: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ],
  "IADES": [
    {"banca": "IADES", "id": "IADES_01", "enunciado": "Questão de Matemática 1 da banca IADES: Calcule o valor de 1 + 2.", "alternativas": ["A) 3", "B) 4", "C) 5", "D) 6", "E) 7"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_02", "enunciado": "Questão de Matemática 2 da banca IADES: Calcule o valor de 2 + 4.", "alternativas": ["A) 6", "B) 8", "C) 10", "D) 12", "E) 14"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_03", "enunciado": "Questão de Matemática 3 da banca IADES: Calcule o valor de 3 + 6.", "alternativas": ["A) 9", "B) 12", "C) 15", "D) 18", "E) 21"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_04", "enunciado": "Questão de Matemática 4 da banca IADES: Calcule o valor de 4 + 8.", "alternativas": ["A) 12", "B) 16", "C) 20", "D) 24", "E) 28"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_05", "enunciado": "Questão de Matemática 5 da banca IADES: Calcule o valor de 5 + 10.", "alternativas": ["A) 15", "B) 20", "C) 25", "D) 30", "E) 35"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_06", "enunciado": "Questão de Matemática 6 da banca IADES: Calcule o valor de 6 + 12.", "alternativas": ["A) 18", "B) 24", "C) 30", "D) 36", "E) 42"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_07", "enunciado": "Questão de Matemática 7 da banca IADES: Calcule o valor de 7 + 14.", "alternativas": ["A) 21", "B) 28", "C) 35", "D) 42", "E) 49"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_08", "enunciado": "Questão de Matemática 8 da banca IADES: Calcule o valor de 8 + 16.", "alternativas": ["A) 24", "B) 32", "C) 40", "D) 48", "E) 56"], "gabarito": "A"},
    {"banca": "IADES", "id": "IADES_09", "enunciado": "Questão de Matemática 9 da banca IADES: Calcule o valor de 9 + 18.", "alternativas": ["A) 27", "B) 36", "C) 45", "D) 54", "E) 63"], "gabarito": "A"}
  ]
};
